### ISSUE TITLE
在windows上安装失败

### ISSUE THREAD

**Issue by tangshi** [lxneng/xpinyin#23]
>    Complete output from command python setup.py egg_info:
>   Traceback (most recent call last):
>      File "<string>", line 20, in <module>
>      File "C:\Users\****\AppData\Local\Temp\pip-build-kr_xe5jj\xpinyin\setup.py", line 7, in <module>
>        README = open(os.path.join(here, 'README.rst')).read()
>    UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 921: illegal multibyte sequence
>
>    ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\****\AppData\Local\Temp\pip-build-kr_xe5jj\xpinyin

**Comment by iaiti** [comment]
pip install xpinyin is okay.

**Comment by huangmingchuan** [comment]
>Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "G:\Users\MINGCH~1\AppData\Local\Temp\pip-build-3ik0nm0a\xpinyin\setup.py", line 7, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x8a in position 921: illegal multibyte sequence

我也是这个错误

**Comment by lxneng** [comment]
@huangmingchuan @tangshi 

已修复，请更新一下最新版本  `pip install -U xpinyin`

**Comment by huangmingchuan** [comment]
@lxneng 
重庆翻译成 Zhongqing，这个有办法解决吗
