### ISSUE TITLE
Where did the tones go?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [lxneng/xpinyin#27]
I just stumbled upon your repository while searching for some xpinyin latex stuff.
From you examples I don't see any tones on the pinyin syllables. Does the program not get them? This would reduce usefulness quite a bit.

**Comment by lxneng** [comment]
@ZelphirKaltstahl  u can use `show_tone_marks` option to `get_pinyin` func enable tones.

```py
In [1]: from xpinyin import Pinyin

In [2]: p = Pinyin()

In [3]: # show tone marks

In [4]: p.get_pinyin(u"上海", show_tone_marks=True)
Out[4]: 'shàng-hǎi'
```

**Comment by ZelphirKaltstahl** [comment]
Thanks, works like a charm!
