### ISSUE TITLE
Please document that words are not accounted for

### ISSUE THREAD

**Issue by dancor** [lxneng/xpinyin#43]
Thank you for the work on this library. A big and easy improvement to its usefulness is to prominently document that it currently performs a character-level translation, which is incorrect for many common words and sentences.

```python
>>> from xpinyin import Pinyin
>>> p = Pinyin()
>>> p.get_pinyin(u"了解")
'le-jie'
```

The output should be
```python
'liao-jie'
```

**Comment by lxneng** [comment]
Chinese polysyllabic characters are complex, and different pronunciations convey different meanings and are used in different ways.

We have now added a new API (`get_pinyins`) to list pinyin combinations.

```python
>>> p.get_pinyins('了解', splitter=' ', tone_marks='marks')                                                               
>>> ['le jiě', 'le jiè', 'le xiè', 'liǎo jiě', 'liǎo jiè', 'liǎo xiè']
```
then u can pick the correct one `'liǎo jiě`
