### ISSUE TITLE
多音字

### ISSUE THREAD

**Issue by shiny** [lxneng/xpinyin#5]
```
>>> p.get_pinyin("西藏")
'xicang'
```

请问是否有支持多音字的计划？
谢谢。

**Comment by mverleg** [comment]
I used this easy hack:

    Pinyin().get_pinyin(chars.replace(u'都', u'兜').replace(u'还', u'孩').replace(u'藏', u'葬'))

Then `"都，还，西藏"` becomes `"dōu， hái， xī zàng"` instead of `"dū， huán， xī cáng"`.
