### ISSUE TITLE
Python 2 support broken: ImportError: No module named pathlib

### ISSUE THREAD

**Issue by sman591** [lxneng/xpinyin#51]
I believe this line (introduced 3 days ago) broke Python 2 support:

https://github.com/lxneng/xpinyin/blob/2f0c7fc06e6d71288a589fb4d3b96b4e9cfa05ab/setup.py#L1

If I understand correctly, [pathlib](https://docs.python.org/3/library/pathlib.html) was introduced in Python 3 as a standard library, but is not readily available to Python 2 environments.

When trying to install a package that imports `xpinyin` on a Python 2 environment, this causes `pip` installation to fail.

```
Collecting xpinyin<1,>=0.5.4
  Downloading xpinyin-0.7.3.tar.gz (131 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-JWNu6W/xpinyin/setup.py'"'"'; __file__='"'"'/tmp/pip-install-JWNu6W/xpinyin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-JWNu6W/xpinyin/pip-egg-info
         cwd: /tmp/pip-install-JWNu6W/xpinyin/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-JWNu6W/xpinyin/setup.py", line 1, in <module>
        from pathlib import Path
    ImportError: No module named pathlib
```

## Workaround for Python 2

Pin to an older version of `xpinyin` in requirements.txt, e.g:

```
xpinyin==0.6.0
```

**Comment by lxneng** [comment]
Sorry, from 0.7.0 we removed Python 2 support.

please pin to 0.6.0.

**Comment by sman591** [comment]
Got it! Thanks for the clarification
